environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"

install:
  - nuget install redis-64 -excludeversion
  - redis-64\tools\redis-server.exe --service-install
  - redis-64\tools\redis-server.exe --service-start
  - pip install -e .
  - pip install pytest-cov
  - pip install coveralls
  - pip install pytest
  - pip install mock

build: off

test_script:
  - py.test --cov rq --durations=5 -s

